services:
  - type: web
    name: bci-enhanced-gui
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bci_rf_ultrasonic_web_sim.py"
    plan: standard
    envVars:
      -key: FLASK_ENV
       value: production
      -key: PYTHON_VERSION
       value: 3.11.6
    
    
